

CREATE TABLE sandstorm.public.age_groups (
   	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
   	RANGE VARCHAR(100) NOT NULL
);

CREATE TABLE sandstorm.public.areas (
   	ID SERIAL PRIMARY KEY,
   	NAME VARCHAR(100) NOT NULL
);

CREATE TABLE sandstorm.public.educations (
   	ID SERIAL PRIMARY KEY,
	LEVEL VARCHAR(100) NOT NULL
);

CREATE TABLE sandstorm.public.users (
   	ID SERIAL PRIMARY KEY,
   	AGE_ID INTEGER,
	AREA_ID INTEGER,
	EDUCATION_ID INTEGER,
	GENDER VARCHAR(1) NOT NULL,
	CONSTRAINT FK_USERS_AGE_GROUPS FOREIGN KEY (AGE_ID) REFERENCES sandstorm.public.age_groups (ID),
	CONSTRAINT FK_USERS_AREAS FOREIGN KEY (AREA_ID) REFERENCES sandstorm.public.areas (ID),
	CONSTRAINT FK_USERS_EDUCATIONS FOREIGN KEY (EDUCATION_ID) REFERENCES sandstorm.public.educations (ID)
);

CREATE TABLE sandstorm.public.devices (
	ID VARCHAR(32) PRIMARY KEY,
    USER_ID INTEGER,
	NAME VARCHAR(100) NOT NULL,
	TOKEN VARCHAR(255) NOT NULL,
	ANDROID_VERSION VARCHAR(60) NOT NULL,
	CONSTRAINT FK_DEVICES_USERS FOREIGN KEY (USER_ID) REFERENCES sandstorm.public.users (ID)
);

CREATE TABLE sandstorm.public.applications (
	ID VARCHAR(32) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PACKAGE_NAME VARCHAR(100) NOT NULL,
	APK_VERSION VARCHAR(60) NOT NULL
);


CREATE TABLE sandstorm.public.resources (
	ID VARCHAR(32) PRIMARY KEY NOT NULL,
	DEVICE_ID VARCHAR(32) NOT NULL,
	APPLICATION_ID VARCHAR(32) NOT NULL,
	CAMERA BOOLEAN DEFAULT FALSE,
	MICROPHONE BOOLEAN DEFAULT FALSE,
	GPS BOOLEAN DEFAULT FALSE,
	CONTACT BOOLEAN DEFAULT FALSE,
	SMS BOOLEAN DEFAULT FALSE,
	MEMORY BOOLEAN DEFAULT FALSE,
    STATUS VARCHAR(6),
	RECORDED_AT TIMESTAMP DEFAULT NOW(),
 	CONSTRAINT FK_RESOURCES_DEVICES FOREIGN KEY (DEVICE_ID) REFERENCES sandstorm.public.devices (ID),
	CONSTRAINT FK_RESOURCES_APPLICATIONS FOREIGN KEY (APPLICATION_ID) REFERENCES sandstorm.public.applications (ID)
);